//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAD_AutoLink.FieldOrder.DataAccessLayer.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FieldOrderEntities : DbContext
    {
        public FieldOrderEntities()
            : base("name=FieldOrderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WEC_API_EXCEPTION_MESSAGES> WEC_API_EXCEPTION_MESSAGES { get; set; }
        public virtual DbSet<WEC_API_STATUS_CODES> WEC_API_STATUS_CODES { get; set; }
        public virtual DbSet<WEC_SOAP_SERVICE_EXCEPTION_LOG> WEC_SOAP_SERVICE_EXCEPTION_LOG { get; set; }
        public virtual DbSet<WEC_SOAP_SERVICE_LOG> WEC_SOAP_SERVICE_LOG { get; set; }
        public virtual DbSet<WEC_CAD_ERROR_CODES> WEC_CAD_ERROR_CODES { get; set; }
        public virtual DbSet<WEC_OUTBOUND_EVENT_TRIGGERS> WEC_OUTBOUND_EVENT_TRIGGERS { get; set; }
        public virtual DbSet<WEC_UDF_DEFINITION> WEC_UDF_DEFINITION { get; set; }
        public virtual DbSet<WEC_DNP_CUTOFF> WEC_DNP_CUTOFF { get; set; }
        public virtual DbSet<WEC_METER_INSPECTION> WEC_METER_INSPECTION { get; set; }
        public virtual DbSet<WEC_CREW_SKILL_MAPPING> WEC_CREW_SKILL_MAPPING { get; set; }
        public virtual DbSet<WEC_API_EXCEPTIONS_LOG> WEC_API_EXCEPTIONS_LOG { get; set; }
        public virtual DbSet<WEC_API_LOG> WEC_API_LOG { get; set; }
        public virtual DbSet<WEC_API_REPORT> WEC_API_REPORT { get; set; }
        public virtual DbSet<WEC_BATCHJOBS> WEC_BATCHJOBS { get; set; }
        public virtual DbSet<WEC_TOPIC_LOG> WEC_TOPIC_LOG { get; set; }
    }
}
