//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldOrder.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEC_TOPIC_LOG
    {
        public decimal ID { get; set; }
        public string SOURCESYSTEM { get; set; }
        public string MESSAGETOPIC { get; set; }
        public string HEADERS { get; set; }
        public string PAYLOAD { get; set; }
        public Nullable<System.DateTimeOffset> MOD_DATETIME { get; set; }
    }
}
