//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldOrder.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEC_CREW_SKILL_MAPPING
    {
        public long ID { get; set; }
        public string SKILL_CODE { get; set; }
        public string SKILL_DESC { get; set; }
        public string PGL_COVERED_TASK { get; set; }
        public string MEA_COVERED_TASK { get; set; }
        public string OPERAND { get; set; }
        public System.DateTime CREATIONDATETIME { get; set; }
        public Nullable<System.DateTime> UPDATEDATETIME { get; set; }
    }
}
