//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldOrder.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEC_BATCHJOBS
    {
        public string JOB_NAME { get; set; }
        public string JOB_DESCRIPTION { get; set; }
        public string JOB_SCHEDULE { get; set; }
        public Nullable<System.DateTime> LAST_RUN_START { get; set; }
        public Nullable<System.DateTime> LAST_RUN_END { get; set; }
    }
}
