//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldOrder.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEC_API_EXCEPTIONS_LOG
    {
        public long ID { get; set; }
        public string EXCEPTIONTYPE { get; set; }
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string STACKTRACE { get; set; }
        public System.DateTime EXCEPTIONDATETIME { get; set; }
    }
}
