//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldOrder.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEC_SOAP_SERVICE_LOG
    {
        public long ID { get; set; }
        public string MACHINE { get; set; }
        public string REQUEST_IP_ADDRESS { get; set; }
        public byte[] REQUEST_CONTENT { get; set; }
        public string REQUEST_URI { get; set; }
        public Nullable<System.DateTime> REQUEST_DATETIME { get; set; }
        public byte[] RESPONSE_CONTENT { get; set; }
        public Nullable<System.DateTime> RESPONSE_DATETIME { get; set; }
        public Nullable<long> API_EXCEPTION_ID { get; set; }
        public string SERVICE_NAME { get; set; }
    }
}
