//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldOrder.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEC_API_LOG
    {
        public long ID { get; set; }
        public string APPLICATION { get; set; }
        public string REQUEST_USER { get; set; }
        public string MACHINE { get; set; }
        public string REQUEST_IP_ADDRESS { get; set; }
        public string REQUEST_CONTENT_TYPE { get; set; }
        public string REQUEST_CONTENT_BODY { get; set; }
        public string REQUEST_URI { get; set; }
        public string REQUEST_METHOD { get; set; }
        public string REQUEST_ROUTE_TEMPLATE { get; set; }
        public string REQUEST_ROUTE_DATA { get; set; }
        public string REQUEST_HEADERS { get; set; }
        public Nullable<System.DateTime> REQUEST_DATETIME { get; set; }
        public string RESPONSE_CONTENT_TYPE { get; set; }
        public string RESPONSE_CONTENT_BODY { get; set; }
        public Nullable<int> RESPONSE_STATUS_CODE { get; set; }
        public string RESPONSE_HEADERS { get; set; }
        public Nullable<System.DateTime> RESPONSE_DATETIME { get; set; }
        public Nullable<long> API_EXCEPTION_ID { get; set; }
        public string EXTERNAL_NO1 { get; set; }
        public string EXTERNAL_NO2 { get; set; }
        public Nullable<System.DateTimeOffset> END_BEFORE_DATE_TIME { get; set; }
        public string FIELD_JOB_ID { get; set; }
        public string MESSAGE_TOPIC { get; set; }
        public string MESSAGE_QUEUE { get; set; }
        public string MESSAGE_ID { get; set; }
        public string MESSAGE_CORRELATION_ID { get; set; }
        public string REQUEST_ID { get; set; }
        public short REVIEWED { get; set; }
    
        public virtual WEC_API_EXCEPTIONS_LOG WEC_API_EXCEPTIONS_LOG { get; set; }
    }
}
