//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldOrder.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEC_API_EXCEPTION_MESSAGES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WEC_API_EXCEPTION_MESSAGES()
        {
            this.WEC_CAD_ERROR_CODES = new HashSet<WEC_CAD_ERROR_CODES>();
        }
    
        public int ID { get; set; }
        public int X_STATUS_CODE { get; set; }
        public string X_RELATED_ELEMENTS { get; set; }
        public string CONTENT_MESSAGE { get; set; }
        public string API { get; set; }
        public string X_STATUS_REASON { get; set; }
    
        public virtual WEC_API_STATUS_CODES WEC_API_STATUS_CODES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WEC_CAD_ERROR_CODES> WEC_CAD_ERROR_CODES { get; set; }
    }
}
