//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldOrder.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEC_UDF_DEFINITION
    {
        public int ID { get; set; }
        public string CATEGORY { get; set; }
        public int CATEGORY_INDEX { get; set; }
        public string CAD_DATA_LABEL { get; set; }
        public string DATA_DESCRIPTION { get; set; }
        public string CAD_MIN_LENGTH { get; set; }
        public string CAD_MAX_LENGTH { get; set; }
        public string CAD_VTB { get; set; }
        public string PRE_POPULATE { get; set; }
        public string DATABASE_TABLE { get; set; }
        public string DATABASE_COLUMN { get; set; }
        public string DATABASE_COLUMN_DEFINITION { get; set; }
        public string INBOUND_FORMATTING { get; set; }
        public string INBOUND_VALIDATION { get; set; }
        public string DATABASE_COMPOSITE_KEY { get; set; }
        public string POPULATE_STORMS { get; set; }
        public string POPULATE_CSS { get; set; }
        public string POPULATE_OMS { get; set; }
        public string POPULATE_OCIS { get; set; }
    }
}
