//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldOrder.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEC_CAD_ERROR_CODES
    {
        public string ERROR_CODE { get; set; }
        public int EXCEPTION_MESSAGES_ID { get; set; }
    
        public virtual WEC_API_EXCEPTION_MESSAGES WEC_API_EXCEPTION_MESSAGES { get; set; }
    }
}
