//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldOrder.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEC_API_STATUS_CODES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WEC_API_STATUS_CODES()
        {
            this.WEC_API_EXCEPTION_MESSAGES = new HashSet<WEC_API_EXCEPTION_MESSAGES>();
        }
    
        public int X_STATUS_CODE { get; set; }
        public string X_STATUS_DESCRIPTION { get; set; }
        public int HTTP_RESPONSE_CODE { get; set; }
        public string HTTP_RESPONSE_MESSAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WEC_API_EXCEPTION_MESSAGES> WEC_API_EXCEPTION_MESSAGES { get; set; }
    }
}
