//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldOrder.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEC_DNP_CUTOFF
    {
        public string ISR_NO { get; set; }
        public string LAST_BILLED_RDG { get; set; }
        public string LAST_BILLED_RDG_DATE { get; set; }
        public string LAST_BILLED_RDG_TYPE { get; set; }
        public string CURRENT_BILL { get; set; }
        public string AMOUNT_ARREARS { get; set; }
        public string BILL_DUE_DATE { get; set; }
        public string ACCOUNT_BALANCE { get; set; }
        public string FIN_NOTICE_EXP_DATE { get; set; }
        public string PENDING_TURN_ON { get; set; }
        public string TURN_ON_HELD { get; set; }
        public string TURN_ON_DATE { get; set; }
        public string PREV_TENANT { get; set; }
        public string OWNER_NAME { get; set; }
        public string OWNER_ADDRESS { get; set; }
        public string MTR_RDG_DISTRICT { get; set; }
        public string MTR_RDG_ROUTE { get; set; }
        public string MTR_RDG_KEY_NBR { get; set; }
        public string ACCT_NO { get; set; }
        public string SUGGEST_OFF_METHOD { get; set; }
        public string HOW_FOUND { get; set; }
        public string HOW_LEFT { get; set; }
        public string MTR_BAR_REMOVED { get; set; }
        public string METER_REMOVED { get; set; }
        public string CUTOFF_LOCATION { get; set; }
        public Nullable<decimal> METER_READING { get; set; }
        public Nullable<decimal> METER_READING_CONF { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
        public string SUGGEST_OFF_METHOD_CODE { get; set; }
    }
}
